Retrieve bound-with information with GraphQL queries
sul-dlss/sul-requests pull request #2439
Opened 2024-05-09 18:23 UTC by cbeer

and introduce `Folio::HoldingsRecord` to match FOLIO data structures (and give us a consistent way to get at the normal + bound-with items).

This includes only the data retrieval parts of #2060 + #2030.

2024-05-17 16:34 UTC, dnoneill requested changes
Bound withs are displaying quite right. See http://localhost:3000/patron_requests/new?barcode=36105029307795&instance_hrid=6290236&origin_location_code=GRE-STACKS

There is only one item so it should not a item selector.

![Screenshot 2024-05-17 at 12 34 22 PM](https://github.com/sul-dlss/sul-requests/assets/19173991/e82ad33e-2fe1-4202-875d-c9310f294e5f)

2024-05-17 16:43 UTC, dnoneill commented
Also I think there might be a problem with the call numbers displaying on this page. Looks like there are repeats which I think isn't quite right. http://localhost:3000/patron_requests/new?instance_hrid=387559&origin_location_code=SAL3-STACKS&step=select

2024-05-17 16:45 UTC, cbeer commented
I'm confused by what I'm seeing in folio-test (but not folio-prod?). It looks like the item says it's bound-with itself?

2024-05-17 16:56 UTC, cbeer commented
It looks like this is a FOLIO model change libsys made recently:
https://github.com/sul-dlss/folio-tasks/issues/304

I'm not sure I understand what's going on, but it seems safe enough to just make sure we don't have duplicated items and hope for the best? (6bfd9e7)

2024-05-17 16:58 UTC, dnoneill commented
Well that is super weird and not what was there originally but yeah I agree making sure the ids are uniq is probably for the best. I remember we had to do that in the original code for reasons I can't remember.

2024-05-20 15:46 UTC, dnoneill commented
Original specs on this had the language as `This item is bound and shelved with:` but it has been updated to `This item is bound and shelved by:`. Was this purposeful? 

Sorting is off in http://localhost:3000/patron_requests/new?instance_hrid=387559&origin_location_code=SAL3-STACKS&step=select (A 1.34 87 is being added to the end. Probably because this is the bound with)

Spacing is a little weird in http://localhost:3000/patron_requests/new?instance_hrid=2969234&origin_location_code=SAL3-STACKS
<img width="856" alt="Screenshot 2024-05-20 at 11 37 29 AM" src="https://github.com/sul-dlss/sul-requests/assets/19173991/45d09c9b-b89d-4ad0-b29e-8877b48f1bb1">

2024-05-20 16:01 UTC, dnoneill approved these changes

2024-05-20 16:02 UTC, dnoneill commented
A couple concerns above that could be addressed with this PR or another.

2024-05-20 16:15 UTC, cbeer commented on app/views/patron_requests/new.html.erb
> +                      <span class="form-check-label ms-1"><%= item&.bound_with_child_holdings_record&.call_number || callnumber_label(item) %></span>
I'm not sure. It's funny the holdings record uses `call_number` but the item uses `callnumber`, and I'm not sure bound-with holdings need any of the other logic 🤷‍♂️

2024-05-20 16:20 UTC, cbeer commented
> Original specs on this had the language as This item is bound and shelved with: but it has been updated to This item is bound and shelved by:. Was this purposeful?

I was going off the figmas. I know we went back and forth on what to call this, but I'm not sure what/where the latest decision is.

> Spacing is a little weird
I've tweaked the call number wrapping (assuming that's the spacing problem you're noting?)
<img width="988" alt="Screenshot 2024-05-20 at 09 20 14" src="https://github.com/sul-dlss/sul-requests/assets/111218/0d878f9f-9700-4545-9602-4a6759540052">

2024-05-20 16:21 UTC, dnoneill commented on app/views/patron_requests/new.html.erb
> +                      <span class="form-check-label ms-1"><%= item&.bound_with_child_holdings_record&.call_number || callnumber_label(item) %></span>
Yeah but couldn't you put into the callnumber_label

`return item.bound_with_child_holdings_record.call_number if item.bound_with_child_holdings_record` or something along those lines?

2024-05-20 16:22 UTC, dnoneill commented
Figmas were probably correct. And yes. That is the spacing problem I was referring to.

2024-06-10 17:53 UTC, merged